version: '3'

services:
  delos:
    container_name: rap2-delos
    # build from ./Dockerfile
#    build: .
    # build from images
    image: blackdog1987/rap2-delos:1.0.0
    environment:
      # mysql config
      - MYSQL_URL=mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWD=123456
      - MYSQL_SCHEMA=rap2

      # redis config
      - REDIS_URL=redis
      - REDIS_PORT=6379

      # production / development
      - NODE_ENV=production
    working_dir: /app
    privileged: true
    ###### 'sleep 30 && node scripts/init' will drop the tables
    ###### RUN ONLY ONCE THEN REMOVE 'sleep 30 && node scripts/init'
    command: /bin/sh -c 'sleep 30; node scripts/init; node dispatch.js'
    ports:
      - 9003:8080

networks:
  default:
    external:
      name: docker-net