version: '3.1'

services:

  redmine:
    image: redmine:3.4.6
    container_name: redmine
    restart: always
    ports:
      - 9002:3000
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_PASSWORD: 123456
    volumes:
      - $HOME/data/docker/downloads:/root/downloads

networks:
  default:
    external:
      name: docker-net