version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - $HOME/data/docker/mysql-data:/var/lib/mysql