version: '3'

services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    ports:
      - 6380:6379
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - $HOME/data/docker/redis:/bitnami

networks:
  default:
    external:
      name: docker-net